// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/quotes.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeframeEnum int32

const (
	TimeframeEnum_TIMEFRAME_UNSPECIFIED TimeframeEnum = 0
	TimeframeEnum_TIMEFRAME_1M          TimeframeEnum = 1
	TimeframeEnum_TIMEFRAME_5M          TimeframeEnum = 2
	TimeframeEnum_TIMEFRAME_15M         TimeframeEnum = 3
	TimeframeEnum_TIMEFRAME_30M         TimeframeEnum = 4
	TimeframeEnum_TIMEFRAME_1H          TimeframeEnum = 5
	TimeframeEnum_TIMEFRAME_4H          TimeframeEnum = 6
	TimeframeEnum_TIMEFRAME_1D          TimeframeEnum = 7
	TimeframeEnum_TIMEFRAME_1W          TimeframeEnum = 8
)

// Enum value maps for TimeframeEnum.
var (
	TimeframeEnum_name = map[int32]string{
		0: "TIMEFRAME_UNSPECIFIED",
		1: "TIMEFRAME_1M",
		2: "TIMEFRAME_5M",
		3: "TIMEFRAME_15M",
		4: "TIMEFRAME_30M",
		5: "TIMEFRAME_1H",
		6: "TIMEFRAME_4H",
		7: "TIMEFRAME_1D",
		8: "TIMEFRAME_1W",
	}
	TimeframeEnum_value = map[string]int32{
		"TIMEFRAME_UNSPECIFIED": 0,
		"TIMEFRAME_1M":          1,
		"TIMEFRAME_5M":          2,
		"TIMEFRAME_15M":         3,
		"TIMEFRAME_30M":         4,
		"TIMEFRAME_1H":          5,
		"TIMEFRAME_4H":          6,
		"TIMEFRAME_1D":          7,
		"TIMEFRAME_1W":          8,
	}
)

func (x TimeframeEnum) Enum() *TimeframeEnum {
	p := new(TimeframeEnum)
	*p = x
	return p
}

func (x TimeframeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeframeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_quotes_proto_enumTypes[0].Descriptor()
}

func (TimeframeEnum) Type() protoreflect.EnumType {
	return &file_api_quotes_proto_enumTypes[0]
}

func (x TimeframeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeframeEnum.Descriptor instead.
func (TimeframeEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{0}
}

type IndicatorTypeEnum int32

const (
	IndicatorTypeEnum_INDICATOR_TYPE_UNSPECIFIED IndicatorTypeEnum = 0
	IndicatorTypeEnum_INDICATOR_TYPE_SMA         IndicatorTypeEnum = 1
	IndicatorTypeEnum_INDICATOR_TYPE_EMA         IndicatorTypeEnum = 2
	IndicatorTypeEnum_INDICATOR_TYPE_DEMA        IndicatorTypeEnum = 3
	IndicatorTypeEnum_INDICATOR_TYPE_TEMA        IndicatorTypeEnum = 4
	IndicatorTypeEnum_INDICATOR_TYPE_TEMA_ZERO   IndicatorTypeEnum = 5
)

// Enum value maps for IndicatorTypeEnum.
var (
	IndicatorTypeEnum_name = map[int32]string{
		0: "INDICATOR_TYPE_UNSPECIFIED",
		1: "INDICATOR_TYPE_SMA",
		2: "INDICATOR_TYPE_EMA",
		3: "INDICATOR_TYPE_DEMA",
		4: "INDICATOR_TYPE_TEMA",
		5: "INDICATOR_TYPE_TEMA_ZERO",
	}
	IndicatorTypeEnum_value = map[string]int32{
		"INDICATOR_TYPE_UNSPECIFIED": 0,
		"INDICATOR_TYPE_SMA":         1,
		"INDICATOR_TYPE_EMA":         2,
		"INDICATOR_TYPE_DEMA":        3,
		"INDICATOR_TYPE_TEMA":        4,
		"INDICATOR_TYPE_TEMA_ZERO":   5,
	}
)

func (x IndicatorTypeEnum) Enum() *IndicatorTypeEnum {
	p := new(IndicatorTypeEnum)
	*p = x
	return p
}

func (x IndicatorTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndicatorTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_quotes_proto_enumTypes[1].Descriptor()
}

func (IndicatorTypeEnum) Type() protoreflect.EnumType {
	return &file_api_quotes_proto_enumTypes[1]
}

func (x IndicatorTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndicatorTypeEnum.Descriptor instead.
func (IndicatorTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{1}
}

type SourceTypeEnum int32

const (
	SourceTypeEnum_SOURCE_TYPE_UNSPECIFIED SourceTypeEnum = 0
	SourceTypeEnum_SOURCE_TYPE_L           SourceTypeEnum = 1
	SourceTypeEnum_SOURCE_TYPE_O           SourceTypeEnum = 2
	SourceTypeEnum_SOURCE_TYPE_C           SourceTypeEnum = 3
	SourceTypeEnum_SOURCE_TYPE_H           SourceTypeEnum = 4
	SourceTypeEnum_SOURCE_TYPE_LO          SourceTypeEnum = 5
	SourceTypeEnum_SOURCE_TYPE_LC          SourceTypeEnum = 6
	SourceTypeEnum_SOURCE_TYPE_LH          SourceTypeEnum = 7
	SourceTypeEnum_SOURCE_TYPE_OC          SourceTypeEnum = 8
	SourceTypeEnum_SOURCE_TYPE_OH          SourceTypeEnum = 9
	SourceTypeEnum_SOURCE_TYPE_CH          SourceTypeEnum = 10
	SourceTypeEnum_SOURCE_TYPE_LOC         SourceTypeEnum = 11
	SourceTypeEnum_SOURCE_TYPE_LOH         SourceTypeEnum = 12
	SourceTypeEnum_SOURCE_TYPE_LCH         SourceTypeEnum = 13
	SourceTypeEnum_SOURCE_TYPE_OCH         SourceTypeEnum = 14
)

// Enum value maps for SourceTypeEnum.
var (
	SourceTypeEnum_name = map[int32]string{
		0:  "SOURCE_TYPE_UNSPECIFIED",
		1:  "SOURCE_TYPE_L",
		2:  "SOURCE_TYPE_O",
		3:  "SOURCE_TYPE_C",
		4:  "SOURCE_TYPE_H",
		5:  "SOURCE_TYPE_LO",
		6:  "SOURCE_TYPE_LC",
		7:  "SOURCE_TYPE_LH",
		8:  "SOURCE_TYPE_OC",
		9:  "SOURCE_TYPE_OH",
		10: "SOURCE_TYPE_CH",
		11: "SOURCE_TYPE_LOC",
		12: "SOURCE_TYPE_LOH",
		13: "SOURCE_TYPE_LCH",
		14: "SOURCE_TYPE_OCH",
	}
	SourceTypeEnum_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED": 0,
		"SOURCE_TYPE_L":           1,
		"SOURCE_TYPE_O":           2,
		"SOURCE_TYPE_C":           3,
		"SOURCE_TYPE_H":           4,
		"SOURCE_TYPE_LO":          5,
		"SOURCE_TYPE_LC":          6,
		"SOURCE_TYPE_LH":          7,
		"SOURCE_TYPE_OC":          8,
		"SOURCE_TYPE_OH":          9,
		"SOURCE_TYPE_CH":          10,
		"SOURCE_TYPE_LOC":         11,
		"SOURCE_TYPE_LOH":         12,
		"SOURCE_TYPE_LCH":         13,
		"SOURCE_TYPE_OCH":         14,
	}
)

func (x SourceTypeEnum) Enum() *SourceTypeEnum {
	p := new(SourceTypeEnum)
	*p = x
	return p
}

func (x SourceTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_quotes_proto_enumTypes[2].Descriptor()
}

func (SourceTypeEnum) Type() protoreflect.EnumType {
	return &file_api_quotes_proto_enumTypes[2]
}

func (x SourceTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceTypeEnum.Descriptor instead.
func (SourceTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{2}
}

type QuotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Tf            TimeframeEnum          `protobuf:"varint,2,opt,name=tf,proto3,enum=api.TimeframeEnum" json:"tf,omitempty"`
	Takeprofit    float64                `protobuf:"fixed64,3,opt,name=takeprofit,proto3" json:"takeprofit,omitempty"`
	Stoploss      float64                `protobuf:"fixed64,4,opt,name=stoploss,proto3" json:"stoploss,omitempty"`
	Ind1          *Indicator             `protobuf:"bytes,5,opt,name=ind1,proto3" json:"ind1,omitempty"`
	Ind2          *Indicator             `protobuf:"bytes,6,opt,name=ind2,proto3" json:"ind2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotesRequest) Reset() {
	*x = QuotesRequest{}
	mi := &file_api_quotes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotesRequest) ProtoMessage() {}

func (x *QuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quotes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotesRequest.ProtoReflect.Descriptor instead.
func (*QuotesRequest) Descriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{0}
}

func (x *QuotesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QuotesRequest) GetTf() TimeframeEnum {
	if x != nil {
		return x.Tf
	}
	return TimeframeEnum_TIMEFRAME_UNSPECIFIED
}

func (x *QuotesRequest) GetTakeprofit() float64 {
	if x != nil {
		return x.Takeprofit
	}
	return 0
}

func (x *QuotesRequest) GetStoploss() float64 {
	if x != nil {
		return x.Stoploss
	}
	return 0
}

func (x *QuotesRequest) GetInd1() *Indicator {
	if x != nil {
		return x.Ind1
	}
	return nil
}

func (x *QuotesRequest) GetInd2() *Indicator {
	if x != nil {
		return x.Ind2
	}
	return nil
}

type Indicator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IndicatorTypeEnum      `protobuf:"varint,1,opt,name=type,proto3,enum=api.IndicatorTypeEnum" json:"type,omitempty"`
	Coef          float64                `protobuf:"fixed64,2,opt,name=coef,proto3" json:"coef,omitempty"`
	Source        SourceTypeEnum         `protobuf:"varint,3,opt,name=source,proto3,enum=api.SourceTypeEnum" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Indicator) Reset() {
	*x = Indicator{}
	mi := &file_api_quotes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicator) ProtoMessage() {}

func (x *Indicator) ProtoReflect() protoreflect.Message {
	mi := &file_api_quotes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indicator.ProtoReflect.Descriptor instead.
func (*Indicator) Descriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{1}
}

func (x *Indicator) GetType() IndicatorTypeEnum {
	if x != nil {
		return x.Type
	}
	return IndicatorTypeEnum_INDICATOR_TYPE_UNSPECIFIED
}

func (x *Indicator) GetCoef() float64 {
	if x != nil {
		return x.Coef
	}
	return 0
}

func (x *Indicator) GetSource() SourceTypeEnum {
	if x != nil {
		return x.Source
	}
	return SourceTypeEnum_SOURCE_TYPE_UNSPECIFIED
}

type QuotesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Time          []*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=time,proto3" json:"time,omitempty"`
	Candles       *Candles                 `protobuf:"bytes,2,opt,name=candles,proto3" json:"candles,omitempty"`
	Indicator1    *Prices                  `protobuf:"bytes,3,opt,name=indicator1,proto3" json:"indicator1,omitempty"`
	Indicator2    *Prices                  `protobuf:"bytes,4,opt,name=indicator2,proto3" json:"indicator2,omitempty"`
	Deals         []*Deal                  `protobuf:"bytes,5,rep,name=deals,proto3" json:"deals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotesResponse) Reset() {
	*x = QuotesResponse{}
	mi := &file_api_quotes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotesResponse) ProtoMessage() {}

func (x *QuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quotes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotesResponse.ProtoReflect.Descriptor instead.
func (*QuotesResponse) Descriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{2}
}

func (x *QuotesResponse) GetTime() []*timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *QuotesResponse) GetCandles() *Candles {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *QuotesResponse) GetIndicator1() *Prices {
	if x != nil {
		return x.Indicator1
	}
	return nil
}

func (x *QuotesResponse) GetIndicator2() *Prices {
	if x != nil {
		return x.Indicator2
	}
	return nil
}

func (x *QuotesResponse) GetDeals() []*Deal {
	if x != nil {
		return x.Deals
	}
	return nil
}

type Prices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         []float64              `protobuf:"fixed64,1,rep,packed,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prices) Reset() {
	*x = Prices{}
	mi := &file_api_quotes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prices) ProtoMessage() {}

func (x *Prices) ProtoReflect() protoreflect.Message {
	mi := &file_api_quotes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prices.ProtoReflect.Descriptor instead.
func (*Prices) Descriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{3}
}

func (x *Prices) GetPrice() []float64 {
	if x != nil {
		return x.Price
	}
	return nil
}

type Candles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L             *Prices                `protobuf:"bytes,1,opt,name=l,proto3" json:"l,omitempty"`
	O             *Prices                `protobuf:"bytes,2,opt,name=o,proto3" json:"o,omitempty"`
	C             *Prices                `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	H             *Prices                `protobuf:"bytes,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candles) Reset() {
	*x = Candles{}
	mi := &file_api_quotes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candles) ProtoMessage() {}

func (x *Candles) ProtoReflect() protoreflect.Message {
	mi := &file_api_quotes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candles.ProtoReflect.Descriptor instead.
func (*Candles) Descriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{4}
}

func (x *Candles) GetL() *Prices {
	if x != nil {
		return x.L
	}
	return nil
}

func (x *Candles) GetO() *Prices {
	if x != nil {
		return x.O
	}
	return nil
}

func (x *Candles) GetC() *Prices {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Candles) GetH() *Prices {
	if x != nil {
		return x.H
	}
	return nil
}

type Deal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          int32                  `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`   // индекс открытия сделки
	Close         int32                  `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"` // индекс закрытия сделки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deal) Reset() {
	*x = Deal{}
	mi := &file_api_quotes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deal) ProtoMessage() {}

func (x *Deal) ProtoReflect() protoreflect.Message {
	mi := &file_api_quotes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deal.ProtoReflect.Descriptor instead.
func (*Deal) Descriptor() ([]byte, []int) {
	return file_api_quotes_proto_rawDescGZIP(), []int{5}
}

func (x *Deal) GetOpen() int32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Deal) GetClose() int32 {
	if x != nil {
		return x.Close
	}
	return 0
}

var File_api_quotes_proto protoreflect.FileDescriptor

const file_api_quotes_proto_rawDesc = "" +
	"\n" +
	"\x10api/quotes.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\rQuotesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\"\n" +
	"\x02tf\x18\x02 \x01(\x0e2\x12.api.TimeframeEnumR\x02tf\x12\x1e\n" +
	"\n" +
	"takeprofit\x18\x03 \x01(\x01R\n" +
	"takeprofit\x12\x1a\n" +
	"\bstoploss\x18\x04 \x01(\x01R\bstoploss\x12\"\n" +
	"\x04ind1\x18\x05 \x01(\v2\x0e.api.IndicatorR\x04ind1\x12\"\n" +
	"\x04ind2\x18\x06 \x01(\v2\x0e.api.IndicatorR\x04ind2\"x\n" +
	"\tIndicator\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.api.IndicatorTypeEnumR\x04type\x12\x12\n" +
	"\x04coef\x18\x02 \x01(\x01R\x04coef\x12+\n" +
	"\x06source\x18\x03 \x01(\x0e2\x13.api.SourceTypeEnumR\x06source\"\xe3\x01\n" +
	"\x0eQuotesResponse\x12.\n" +
	"\x04time\x18\x01 \x03(\v2\x1a.google.protobuf.TimestampR\x04time\x12&\n" +
	"\acandles\x18\x02 \x01(\v2\f.api.CandlesR\acandles\x12+\n" +
	"\n" +
	"indicator1\x18\x03 \x01(\v2\v.api.PricesR\n" +
	"indicator1\x12+\n" +
	"\n" +
	"indicator2\x18\x04 \x01(\v2\v.api.PricesR\n" +
	"indicator2\x12\x1f\n" +
	"\x05deals\x18\x05 \x03(\v2\t.api.DealR\x05deals\"\x1e\n" +
	"\x06Prices\x12\x14\n" +
	"\x05price\x18\x01 \x03(\x01R\x05price\"u\n" +
	"\aCandles\x12\x19\n" +
	"\x01l\x18\x01 \x01(\v2\v.api.PricesR\x01l\x12\x19\n" +
	"\x01o\x18\x02 \x01(\v2\v.api.PricesR\x01o\x12\x19\n" +
	"\x01c\x18\x03 \x01(\v2\v.api.PricesR\x01c\x12\x19\n" +
	"\x01h\x18\x04 \x01(\v2\v.api.PricesR\x01h\"0\n" +
	"\x04Deal\x12\x12\n" +
	"\x04open\x18\x01 \x01(\x05R\x04open\x12\x14\n" +
	"\x05close\x18\x02 \x01(\x05R\x05close*\xbc\x01\n" +
	"\rTimeframeEnum\x12\x19\n" +
	"\x15TIMEFRAME_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTIMEFRAME_1M\x10\x01\x12\x10\n" +
	"\fTIMEFRAME_5M\x10\x02\x12\x11\n" +
	"\rTIMEFRAME_15M\x10\x03\x12\x11\n" +
	"\rTIMEFRAME_30M\x10\x04\x12\x10\n" +
	"\fTIMEFRAME_1H\x10\x05\x12\x10\n" +
	"\fTIMEFRAME_4H\x10\x06\x12\x10\n" +
	"\fTIMEFRAME_1D\x10\a\x12\x10\n" +
	"\fTIMEFRAME_1W\x10\b*\xb3\x01\n" +
	"\x11IndicatorTypeEnum\x12\x1e\n" +
	"\x1aINDICATOR_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INDICATOR_TYPE_SMA\x10\x01\x12\x16\n" +
	"\x12INDICATOR_TYPE_EMA\x10\x02\x12\x17\n" +
	"\x13INDICATOR_TYPE_DEMA\x10\x03\x12\x17\n" +
	"\x13INDICATOR_TYPE_TEMA\x10\x04\x12\x1c\n" +
	"\x18INDICATOR_TYPE_TEMA_ZERO\x10\x05*\xc5\x02\n" +
	"\x0eSourceTypeEnum\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSOURCE_TYPE_L\x10\x01\x12\x11\n" +
	"\rSOURCE_TYPE_O\x10\x02\x12\x11\n" +
	"\rSOURCE_TYPE_C\x10\x03\x12\x11\n" +
	"\rSOURCE_TYPE_H\x10\x04\x12\x12\n" +
	"\x0eSOURCE_TYPE_LO\x10\x05\x12\x12\n" +
	"\x0eSOURCE_TYPE_LC\x10\x06\x12\x12\n" +
	"\x0eSOURCE_TYPE_LH\x10\a\x12\x12\n" +
	"\x0eSOURCE_TYPE_OC\x10\b\x12\x12\n" +
	"\x0eSOURCE_TYPE_OH\x10\t\x12\x12\n" +
	"\x0eSOURCE_TYPE_CH\x10\n" +
	"\x12\x13\n" +
	"\x0fSOURCE_TYPE_LOC\x10\v\x12\x13\n" +
	"\x0fSOURCE_TYPE_LOH\x10\f\x12\x13\n" +
	"\x0fSOURCE_TYPE_LCH\x10\r\x12\x13\n" +
	"\x0fSOURCE_TYPE_OCH\x10\x0eB\fZ\n" +
	"server/apib\x06proto3"

var (
	file_api_quotes_proto_rawDescOnce sync.Once
	file_api_quotes_proto_rawDescData []byte
)

func file_api_quotes_proto_rawDescGZIP() []byte {
	file_api_quotes_proto_rawDescOnce.Do(func() {
		file_api_quotes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_quotes_proto_rawDesc), len(file_api_quotes_proto_rawDesc)))
	})
	return file_api_quotes_proto_rawDescData
}

var file_api_quotes_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_quotes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_quotes_proto_goTypes = []any{
	(TimeframeEnum)(0),            // 0: api.TimeframeEnum
	(IndicatorTypeEnum)(0),        // 1: api.IndicatorTypeEnum
	(SourceTypeEnum)(0),           // 2: api.SourceTypeEnum
	(*QuotesRequest)(nil),         // 3: api.QuotesRequest
	(*Indicator)(nil),             // 4: api.Indicator
	(*QuotesResponse)(nil),        // 5: api.QuotesResponse
	(*Prices)(nil),                // 6: api.Prices
	(*Candles)(nil),               // 7: api.Candles
	(*Deal)(nil),                  // 8: api.Deal
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_quotes_proto_depIdxs = []int32{
	0,  // 0: api.QuotesRequest.tf:type_name -> api.TimeframeEnum
	4,  // 1: api.QuotesRequest.ind1:type_name -> api.Indicator
	4,  // 2: api.QuotesRequest.ind2:type_name -> api.Indicator
	1,  // 3: api.Indicator.type:type_name -> api.IndicatorTypeEnum
	2,  // 4: api.Indicator.source:type_name -> api.SourceTypeEnum
	9,  // 5: api.QuotesResponse.time:type_name -> google.protobuf.Timestamp
	7,  // 6: api.QuotesResponse.candles:type_name -> api.Candles
	6,  // 7: api.QuotesResponse.indicator1:type_name -> api.Prices
	6,  // 8: api.QuotesResponse.indicator2:type_name -> api.Prices
	8,  // 9: api.QuotesResponse.deals:type_name -> api.Deal
	6,  // 10: api.Candles.l:type_name -> api.Prices
	6,  // 11: api.Candles.o:type_name -> api.Prices
	6,  // 12: api.Candles.c:type_name -> api.Prices
	6,  // 13: api.Candles.h:type_name -> api.Prices
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_quotes_proto_init() }
func file_api_quotes_proto_init() {
	if File_api_quotes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_quotes_proto_rawDesc), len(file_api_quotes_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_quotes_proto_goTypes,
		DependencyIndexes: file_api_quotes_proto_depIdxs,
		EnumInfos:         file_api_quotes_proto_enumTypes,
		MessageInfos:      file_api_quotes_proto_msgTypes,
	}.Build()
	File_api_quotes_proto = out.File
	file_api_quotes_proto_goTypes = nil
	file_api_quotes_proto_depIdxs = nil
}
