server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    client_max_body_size 10M;

    root /var/www/html;
    index index.html;

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ /index.html?$args;
    }

    # GZIP
    gzip                on;
    gzip_min_length     100;
    gzip_proxied        any;
    gzip_comp_level     2;
    gzip_types          application/json text/plain text/css text/json application/x-javascript text/javascript application/javascript;

    gzip_static         on;

    if ( $http_user_agent ~* (nmap|nikto|wikto|sf|sqlmap|bsqlbf|w3af|acunetix|havij|appscan) ) {
        return 444;
    }

    # Media: images, icons, video, audio, HTC
    location ~* (?:assets|layout|themes|plugins|photo)\/.+\.(?:css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz)$ {
        expires 7d;
    	add_header Access-Control-Allow-Origin "*";
        access_log off;
        add_header Cache-Control "public";
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    # Общий прокси для /api/
    location /api/ {
        port_in_redirect    off;
        proxy_redirect      off;
        proxy_pass          http://host.docker.internal:8888/api/;
        proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header    Host             $host;
        proxy_set_header    X-Real-IP        $remote_addr;
    }

    location ~ /\.ht {
       deny all;
    }
}
