// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.34.1
// source: api/quotes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "api";

export const TimeframeEnum = {
  TIMEFRAME_UNSPECIFIED: 0,
  TIMEFRAME_1M: 1,
  TIMEFRAME_5M: 2,
  TIMEFRAME_15M: 3,
  TIMEFRAME_30M: 4,
  TIMEFRAME_1H: 5,
  TIMEFRAME_4H: 6,
  TIMEFRAME_1D: 7,
  TIMEFRAME_1W: 8,
  UNRECOGNIZED: -1,
} as const;

export type TimeframeEnum = typeof TimeframeEnum[keyof typeof TimeframeEnum];

export namespace TimeframeEnum {
  export type TIMEFRAME_UNSPECIFIED = typeof TimeframeEnum.TIMEFRAME_UNSPECIFIED;
  export type TIMEFRAME_1M = typeof TimeframeEnum.TIMEFRAME_1M;
  export type TIMEFRAME_5M = typeof TimeframeEnum.TIMEFRAME_5M;
  export type TIMEFRAME_15M = typeof TimeframeEnum.TIMEFRAME_15M;
  export type TIMEFRAME_30M = typeof TimeframeEnum.TIMEFRAME_30M;
  export type TIMEFRAME_1H = typeof TimeframeEnum.TIMEFRAME_1H;
  export type TIMEFRAME_4H = typeof TimeframeEnum.TIMEFRAME_4H;
  export type TIMEFRAME_1D = typeof TimeframeEnum.TIMEFRAME_1D;
  export type TIMEFRAME_1W = typeof TimeframeEnum.TIMEFRAME_1W;
  export type UNRECOGNIZED = typeof TimeframeEnum.UNRECOGNIZED;
}

export const IndicatorTypeEnum = {
  INDICATOR_TYPE_UNSPECIFIED: 0,
  INDICATOR_TYPE_SMA: 1,
  INDICATOR_TYPE_EMA: 2,
  INDICATOR_TYPE_DEMA: 3,
  INDICATOR_TYPE_TEMA: 4,
  INDICATOR_TYPE_TEMA_ZERO: 5,
  UNRECOGNIZED: -1,
} as const;

export type IndicatorTypeEnum = typeof IndicatorTypeEnum[keyof typeof IndicatorTypeEnum];

export namespace IndicatorTypeEnum {
  export type INDICATOR_TYPE_UNSPECIFIED = typeof IndicatorTypeEnum.INDICATOR_TYPE_UNSPECIFIED;
  export type INDICATOR_TYPE_SMA = typeof IndicatorTypeEnum.INDICATOR_TYPE_SMA;
  export type INDICATOR_TYPE_EMA = typeof IndicatorTypeEnum.INDICATOR_TYPE_EMA;
  export type INDICATOR_TYPE_DEMA = typeof IndicatorTypeEnum.INDICATOR_TYPE_DEMA;
  export type INDICATOR_TYPE_TEMA = typeof IndicatorTypeEnum.INDICATOR_TYPE_TEMA;
  export type INDICATOR_TYPE_TEMA_ZERO = typeof IndicatorTypeEnum.INDICATOR_TYPE_TEMA_ZERO;
  export type UNRECOGNIZED = typeof IndicatorTypeEnum.UNRECOGNIZED;
}

export const SourceTypeEnum = {
  SOURCE_TYPE_UNSPECIFIED: 0,
  SOURCE_TYPE_L: 1,
  SOURCE_TYPE_O: 2,
  SOURCE_TYPE_C: 3,
  SOURCE_TYPE_H: 4,
  SOURCE_TYPE_LO: 5,
  SOURCE_TYPE_LC: 6,
  SOURCE_TYPE_LH: 7,
  SOURCE_TYPE_OC: 8,
  SOURCE_TYPE_OH: 9,
  SOURCE_TYPE_CH: 10,
  SOURCE_TYPE_LOC: 11,
  SOURCE_TYPE_LOH: 12,
  SOURCE_TYPE_LCH: 13,
  SOURCE_TYPE_OCH: 14,
  UNRECOGNIZED: -1,
} as const;

export type SourceTypeEnum = typeof SourceTypeEnum[keyof typeof SourceTypeEnum];

export namespace SourceTypeEnum {
  export type SOURCE_TYPE_UNSPECIFIED = typeof SourceTypeEnum.SOURCE_TYPE_UNSPECIFIED;
  export type SOURCE_TYPE_L = typeof SourceTypeEnum.SOURCE_TYPE_L;
  export type SOURCE_TYPE_O = typeof SourceTypeEnum.SOURCE_TYPE_O;
  export type SOURCE_TYPE_C = typeof SourceTypeEnum.SOURCE_TYPE_C;
  export type SOURCE_TYPE_H = typeof SourceTypeEnum.SOURCE_TYPE_H;
  export type SOURCE_TYPE_LO = typeof SourceTypeEnum.SOURCE_TYPE_LO;
  export type SOURCE_TYPE_LC = typeof SourceTypeEnum.SOURCE_TYPE_LC;
  export type SOURCE_TYPE_LH = typeof SourceTypeEnum.SOURCE_TYPE_LH;
  export type SOURCE_TYPE_OC = typeof SourceTypeEnum.SOURCE_TYPE_OC;
  export type SOURCE_TYPE_OH = typeof SourceTypeEnum.SOURCE_TYPE_OH;
  export type SOURCE_TYPE_CH = typeof SourceTypeEnum.SOURCE_TYPE_CH;
  export type SOURCE_TYPE_LOC = typeof SourceTypeEnum.SOURCE_TYPE_LOC;
  export type SOURCE_TYPE_LOH = typeof SourceTypeEnum.SOURCE_TYPE_LOH;
  export type SOURCE_TYPE_LCH = typeof SourceTypeEnum.SOURCE_TYPE_LCH;
  export type SOURCE_TYPE_OCH = typeof SourceTypeEnum.SOURCE_TYPE_OCH;
  export type UNRECOGNIZED = typeof SourceTypeEnum.UNRECOGNIZED;
}

export interface QuotesRequest {
  symbol: string;
  tf: TimeframeEnum;
  takeprofit: number;
  stoploss: number;
  ind1?: Indicator | undefined;
  ind2?: Indicator | undefined;
}

export interface Indicator {
  type: IndicatorTypeEnum;
  coef: number;
  source: SourceTypeEnum;
}

export interface QuotesResponse {
  candles?: Candles | undefined;
  indicators: Candles[];
  time: Date[];
  deals: Deal[];
}

export interface Candles {
  l: number[];
  o: number[];
  c: number[];
  h: number[];
}

export interface Deal {
  /** индекс открытия сделки */
  open: number;
  /** индекс закрытия сделки */
  close: number;
}

function createBaseQuotesRequest(): QuotesRequest {
  return { symbol: "", tf: 0, takeprofit: 0, stoploss: 0, ind1: undefined, ind2: undefined };
}

export const QuotesRequest: MessageFns<QuotesRequest> = {
  encode(message: QuotesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.tf !== 0) {
      writer.uint32(16).int32(message.tf);
    }
    if (message.takeprofit !== 0) {
      writer.uint32(25).double(message.takeprofit);
    }
    if (message.stoploss !== 0) {
      writer.uint32(33).double(message.stoploss);
    }
    if (message.ind1 !== undefined) {
      Indicator.encode(message.ind1, writer.uint32(42).fork()).join();
    }
    if (message.ind2 !== undefined) {
      Indicator.encode(message.ind2, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuotesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuotesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tf = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.takeprofit = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.stoploss = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ind1 = Indicator.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.ind2 = Indicator.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<QuotesRequest>): QuotesRequest {
    return QuotesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QuotesRequest>): QuotesRequest {
    const message = createBaseQuotesRequest();
    message.symbol = object.symbol ?? "";
    message.tf = object.tf ?? 0;
    message.takeprofit = object.takeprofit ?? 0;
    message.stoploss = object.stoploss ?? 0;
    message.ind1 = (object.ind1 !== undefined && object.ind1 !== null) ? Indicator.fromPartial(object.ind1) : undefined;
    message.ind2 = (object.ind2 !== undefined && object.ind2 !== null) ? Indicator.fromPartial(object.ind2) : undefined;
    return message;
  },
};

function createBaseIndicator(): Indicator {
  return { type: 0, coef: 0, source: 0 };
}

export const Indicator: MessageFns<Indicator> = {
  encode(message: Indicator, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.coef !== 0) {
      writer.uint32(17).double(message.coef);
    }
    if (message.source !== 0) {
      writer.uint32(24).int32(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Indicator {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndicator();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.coef = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.source = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Indicator>): Indicator {
    return Indicator.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Indicator>): Indicator {
    const message = createBaseIndicator();
    message.type = object.type ?? 0;
    message.coef = object.coef ?? 0;
    message.source = object.source ?? 0;
    return message;
  },
};

function createBaseQuotesResponse(): QuotesResponse {
  return { candles: undefined, indicators: [], time: [], deals: [] };
}

export const QuotesResponse: MessageFns<QuotesResponse> = {
  encode(message: QuotesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.candles !== undefined) {
      Candles.encode(message.candles, writer.uint32(10).fork()).join();
    }
    for (const v of message.indicators) {
      Candles.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.time) {
      Timestamp.encode(toTimestamp(v!), writer.uint32(26).fork()).join();
    }
    for (const v of message.deals) {
      Deal.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuotesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuotesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.candles = Candles.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.indicators.push(Candles.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.time.push(fromTimestamp(Timestamp.decode(reader, reader.uint32())));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deals.push(Deal.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<QuotesResponse>): QuotesResponse {
    return QuotesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QuotesResponse>): QuotesResponse {
    const message = createBaseQuotesResponse();
    message.candles = (object.candles !== undefined && object.candles !== null)
      ? Candles.fromPartial(object.candles)
      : undefined;
    message.indicators = object.indicators?.map((e) => Candles.fromPartial(e)) || [];
    message.time = object.time?.map((e) => e) || [];
    message.deals = object.deals?.map((e) => Deal.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCandles(): Candles {
  return { l: [], o: [], c: [], h: [] };
}

export const Candles: MessageFns<Candles> = {
  encode(message: Candles, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.l) {
      writer.double(v);
    }
    writer.join();
    writer.uint32(18).fork();
    for (const v of message.o) {
      writer.double(v);
    }
    writer.join();
    writer.uint32(26).fork();
    for (const v of message.c) {
      writer.double(v);
    }
    writer.join();
    writer.uint32(34).fork();
    for (const v of message.h) {
      writer.double(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Candles {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCandles();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 9) {
            message.l.push(reader.double());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.l.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag === 17) {
            message.o.push(reader.double());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.o.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag === 25) {
            message.c.push(reader.double());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.c.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag === 33) {
            message.h.push(reader.double());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.h.push(reader.double());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Candles>): Candles {
    return Candles.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Candles>): Candles {
    const message = createBaseCandles();
    message.l = object.l?.map((e) => e) || [];
    message.o = object.o?.map((e) => e) || [];
    message.c = object.c?.map((e) => e) || [];
    message.h = object.h?.map((e) => e) || [];
    return message;
  },
};

function createBaseDeal(): Deal {
  return { open: 0, close: 0 };
}

export const Deal: MessageFns<Deal> = {
  encode(message: Deal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.open !== 0) {
      writer.uint32(8).int32(message.open);
    }
    if (message.close !== 0) {
      writer.uint32(16).int32(message.close);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Deal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.open = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.close = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Deal>): Deal {
    return Deal.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Deal>): Deal {
    const message = createBaseDeal();
    message.open = object.open ?? 0;
    message.close = object.close ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
