analyzer:
  decimals: 3
  takeprofit:
    start: 10
    end: 150
    step: 2
  stoploss:
    start: 8
    end: 30
    step: 2

  indicators:
    # 1-ая группа индикаторов
    -
      - type: sma
        coefs:
          start: 3.0
          end: 15.0
          step: 1.0
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

      - type: ema
        coefs:
          start: 0.2
          end: 1.5
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH
      - type: dema
        coefs:
          start: 0.2
          end: 1.5
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

      - type: tema
        coefs:
          start: 0.2
          end: 1.5
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

      - type: temaZero
        coefs:
          start: 0.2
          end: 1.6
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

    # 2-ая группа индикаторов
    -
      - type: sma
        coefs:
          start: 3.0
          end: 15.0
          step: 1.0
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

      - type: ema
        coefs:
          start: 0.2
          end: 1.5
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

      - type: dema
        coefs:
          start: 0.2
          end: 1.5
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

      - type: tema
        coefs:
          start: 0.2
          end: 1.5
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH

      - type: temaZero
        coefs:
          start: 0.2
          end: 1.6
          step: 0.1
        sources:
          - L
          - O
          - C
          - H
          - LO
          - LC
          - LH
          - OC
          - OH
          - CH
          - LOC
          - LOH
          - LCH
          - OCH
